services:
  database:
    build:
      context: ./database
    container_name: coupon-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  wiremock:
    image: wiremock/wiremock:3.13.2
    container_name: wiremock-ip-resolver
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    ports:
      - "${WIREMOCK_PORT}:8080"
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

  backend:
    build:
      context: ./service
    container_name: coupon-service
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - IPAPI_URL=${IPAPI_URL:-http://ip-api.com/json}
      - java.net.preferIPv4Stack=true
    depends_on:
      - database
      - wiremock

volumes:
  pgdata: